export const INITIAL_SEED_POSTS = [
  {
    id: 'promo_ai_audit',
    businessId: 'biz_apex',
    businessName: 'Apex Tech Solutions',
    businessLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
    allianceId: 'all_blr',
    title: 'Complimentary AI & Automation Assessment',
    shortDescription: 'Discover how custom AI agents can automate 40% of your business operations in 30 days.',
    description: 'Exclusive offer for Spin City Alliance members! Apex Tech Solutions is offering a complete 2-week technical assessment. Our senior engineers will audit your existing workflow, pinpoint manual bottlenecks, and build a tailored AI integration blueprint.',
    categoryName: 'IT & Software Solutions',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
    offer: '100% Free Audit ($2,500 standard fee waived)',
    startDate: '2026-08-01',
    endDate: '2026-09-30',
    cta: 'Claim Free AI Audit',
    destinationUrl: 'https://apextech.io/sca-audit',
    shareHeadline: '🚀 Exclusive AI Audit Offer for Business Leaders',
    shareMessage: 'Our trusted tech partner Apex Tech Solutions is providing free AI readiness audits for business owners this month. Automate your manual workflows! Check it out:',
    status: 'LIVE',
    estimatedReach: 28500,
    views: 412,
    clicks: 128,
    shares: 34,
    leadsCount: 18,
    referralsCount: 6,
    reportedSalesCount: 4,
    estimatedRevenue: 15000,
    resultsCount: 14,
    membersPromotingCount: 8,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    recommended: true,
  },
  {
    id: 'promo_office_space',
    businessId: 'biz_horizon',
    businessName: 'Horizon Realty Group',
    businessLogo: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=200&auto=format&fit=crop&q=80',
    allianceId: 'all_blr',
    title: 'Indiranagar Prime Office Lease - SCA Discount',
    shortDescription: 'Grade-A 5,000 sq ft plug-and-play office space with zero broker commission.',
    description: 'Looking to expand or upgrade your office location? Horizon Realty has secured an exclusive Grade-A commercial floor in Indiranagar. Completely furnished with 60 workstations, 4 conference rooms, cafeteria, and 100% power backup.',
    categoryName: 'Commercial Real Estate',
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80',
    offer: 'Zero Brokerage Fee + 1 Month Free Rent',
    startDate: '2026-08-05',
    endDate: '2026-09-15',
    cta: 'Book Private Site Visit',
    destinationUrl: 'https://horizonrealty.in/indiranagar-prime',
    shareHeadline: '🏢 Premium Office Space Available in Indiranagar',
    shareMessage: 'Planning office expansion? Check out Horizon Realty’s exclusive Grade-A property with zero brokerage for alliance members!',
    status: 'LIVE',
    estimatedReach: 24000,
    views: 290,
    clicks: 86,
    shares: 19,
    leadsCount: 12,
    referralsCount: 4,
    reportedSalesCount: 2,
    estimatedRevenue: 28000,
    resultsCount: 6,
    membersPromotingCount: 5,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    recommended: true,
  },
  {
    id: 'promo_interior_design',
    businessId: 'biz_designcraft',
    businessName: 'DesignCraft Studio',
    businessLogo: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=200&auto=format&fit=crop&q=80',
    allianceId: 'all_blr',
    title: '3D Virtual Office Fitout Design Package',
    shortDescription: 'Visualize your office redesign in photorealistic 3D before spending a single rupee.',
    description: 'DesignCraft Studio is revolutionizing workspace interiors. We provide complete 3D VR architectural walkthroughs, ergonomic furniture layouts, and sustainable materials selection.',
    categoryName: 'Interior Architecture & Design',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    offer: 'Free 3D Architectural VR Render',
    startDate: '2026-08-10',
    endDate: '2026-10-01',
    cta: 'Request 3D Rendering',
    destinationUrl: 'https://designcraft.design/vr-workspace',
    shareHeadline: '🎨 Elevate Your Workspace Design with 3D VR Renders',
    shareMessage: 'Transform your office into a modern, inspiring workspace! DesignCraft Studio is offering free 3D architectural renders for alliance members:',
    status: 'LIVE',
    estimatedReach: 18500,
    views: 185,
    clicks: 64,
    shares: 15,
    leadsCount: 8,
    referralsCount: 3,
    reportedSalesCount: 1,
    estimatedRevenue: 12000,
    resultsCount: 4,
    membersPromotingCount: 4,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    recommended: true,
  },
];
